### ISSUE TITLE
high dynamic range loses info

### ISSUE THREAD

**Issue by frueter** [rafaelperez/RIFE-for-Nuke#5]
I just had a quick play with this comparing it to a very troublesome retime I had on my last shot. It's looking great, thank you so much for sharing!
I just noticed that in overexposed areas (e.g. white striped shirt in direct sun light) the results were clamped at 1.30831.
![image](https://github.com/rafaelperez/RIFE-for-Nuke/assets/1725483/ab6f5c13-de90-4f31-ba58-e6b84a79ea79)

Easy workaround is to stop the plate down for retime which solved that issue.
![image](https://github.com/rafaelperez/RIFE-for-Nuke/assets/1725483/8b2c6b4f-d7bd-43c1-a077-c7850c471ce2)

I assume this is a limitation with the model?!
Great to have this in the toolbox!

**Comment by rafaelperez** [comment]
Thanks for reporting this @frueter and thanks to @manwhosoldthew for providing the solution.
I've applied and tested the fix on my end and it looks good.
I just released a new version that includes this fix.
